---
version: 2
plugins:
  duplication:
    enabled: true
    config:
      languages:
        python:
          python_version: 3
          mass_threshold: 40
  eslint:
    enabled: true
  fixme:
    enabled: true
  pep8:
    enabled: true
    checks:
      E501:
        enabled: false
  radon:
    enabled: true
    config:
      threshold: "C"
checks:
  argument-count:
    config:
      threshold: 10
  method-complexity:
    config:
      threshold: 10
exclude_patterns:
- config/
- node_modules/
- test/
