---
engines:
  duplication:
    enabled: true
    config:
      languages:
      - javascript
      - python
  eslint:
    enabled: true
  fixme:
    enabled: true
  pep8:
    enabled: true
    checks:
      E501:
        enabled: false
  radon:
    enabled:
    config:
      threshold: "C"
checks:
  argument-count:
    config:
      threshold: 10
  method-complexity:
    config:
      threshold: 10
ratings:
  paths:
  - "**.js"
  - "**.py"
exclude_paths:
- config/
- node_modules/
