# CrossQ Atari
# Same as SAC Atari but: CrossQ algorithm, training_iter=1, no target networks.
# ConvNet body: Nature CNN [32,64,64] + 512fc, normalize=true for uint8→float on GPU.

crossq_atari_arc:
  agent:
    name: CrossQ
    algorithm:
      name: CrossQ
      action_pdtype: Categorical
      action_policy: default
      gamma: 0.99
      training_start_step: 1000
      training_frequency: 4
      training_iter: 1
    memory:
      name: Replay
      batch_size: 256
      max_size: 200000
      use_cer: false
    net:
      type: ConvNet
      hid_layers_activation: relu
      init_fn: orthogonal_
      clip_grad_val: 0.5
      use_same_optim: false
      loss_spec:
        name: SmoothL1Loss
      optim_spec:
        name: AdamW
        lr: 3.0e-4
        eps: 1.0e-4
      normalize: true
      gpu: auto
  env:
    name: ${env}
    num_envs: 16
    max_t: null
    max_frame: 2000000
    life_loss_info: true
  meta:
    distributed: false
    eval_frequency: 10000
    log_frequency: 10000
    max_session: 4
    max_trial: 1
