# PPO-SIL Classic Control - TorchArcNet specs
# Covers: CartPole-v1, Acrobot-v1

# -- Shared anchors --

_sil_meta: &sil_meta
  distributed: false
  log_frequency: 500
  eval_frequency: 256
  max_session: 4
  max_trial: 1

_sil_net: &sil_net
  type: TorchArcNet
  shared: false
  arc:
    modules:
      body:
        Sequential:
          - LazyLinear: {out_features: 64}
          - Tanh:
          - LazyLinear: {out_features: 64}
          - Tanh:
    graph:
      input: x
      modules:
        body: [x]
      output: body
  hid_layers_activation: tanh
  clip_grad_val: 0.5
  use_same_optim: false
  loss_spec:
    name: MSELoss
  gpu: auto

_sil_algorithm: &sil_algorithm
  name: PPOSIL
  action_pdtype: default
  action_policy: default
  explore_var_spec: null
  gamma: 0.99
  lam: 0.95
  clip_eps_spec: &clip_02
    name: no_decay
    start_val: 0.2
    end_val: 0.2
    start_step: 0
    end_step: 0
  entropy_coef_spec: &entropy_001
    name: no_decay
    start_val: 0.01
    end_val: 0.01
    start_step: 0
    end_step: 0
  val_loss_coef: 0.5
  sil_policy_loss_coef: 1.0
  sil_val_loss_coef: 0.01
  time_horizon: 256
  minibatch_size: 128
  training_batch_iter: 4
  training_iter: 4
  training_epoch: 10

_sil_memory: &sil_memory
  name: OnPolicyBatchReplay
  sil_replay_name: Replay
  batch_size: 128
  max_size: 10000
  use_cer: true

# -- Specs --

ppo_sil_cartpole_arc:
  agent:
    name: PPOSIL
    algorithm:
      <<: *sil_algorithm
    memory:
      <<: *sil_memory
    net:
      <<: *sil_net
      actor_optim_spec:
        name: Adam
        lr: 0.0003
      critic_optim_spec:
        name: Adam
        lr: 0.0003
  env:
    name: CartPole-v1
    num_envs: 4
    max_t: null
    max_frame: 200000
  meta:
    <<: *sil_meta

ppo_sil_acrobot_arc:
  agent:
    name: PPOSIL
    algorithm:
      <<: *sil_algorithm
      gamma: 0.995
      lam: 0.947
      sil_policy_loss_coef: 0.58
      sil_val_loss_coef: 0.029
      minibatch_size: 64
      normalize_v_targets: true
    memory:
      <<: *sil_memory
    net:
      <<: *sil_net
      init_fn: orthogonal_
      actor_init_std: 0.01
      critic_init_std: 1.0
      actor_optim_spec:
        name: AdamW
        lr: 0.00012
      critic_optim_spec:
        name: AdamW
        lr: 0.00174
  env:
    name: Acrobot-v1
    num_envs: 4
    max_t: null
    max_frame: 500000
  meta:
    <<: *sil_meta
    eval_frequency: 500
    rigorous_eval: 0
    max_trial: 20
    search_resources:
      cpu: 1
      gpu: 0.125
    search_scheduler:
      grace_period: 50000
      reduction_factor: 3
  search:
    agent.algorithm.gamma__uniform: [0.98, 0.999]
    agent.algorithm.lam__uniform: [0.9, 0.98]
    agent.algorithm.sil_policy_loss_coef__loguniform: [0.5, 2.0]
    agent.algorithm.sil_val_loss_coef__loguniform: [0.005, 0.05]
    agent.net.actor_optim_spec.lr__loguniform: [0.0001, 0.001]
    agent.net.critic_optim_spec.lr__loguniform: [0.0005, 0.003]
