# PPO MuJoCo using TorchArcNet - equivalent to ppo_mujoco.json with MLPNet
# The 'arc' block defines the body/feature extractor using torcharc YAML format.
# Output heads are added automatically by SLM-Lab based on action space.

ppo_mujoco_arc:
  agent:
    name: PPO
    algorithm:
      name: PPO
      action_pdtype: default
      action_policy: default
      explore_var_spec: null
      gamma: 0.99
      lam: 0.95
      clip_eps_spec:
        name: no_decay
        start_val: 0.2
        end_val: 0.2
        start_step: 0
        end_step: 0
      entropy_coef_spec:
        name: no_decay
        start_val: 0.0
        end_val: 0.0
        start_step: 0
        end_step: 0
      val_loss_coef: 0.5
      time_horizon: 2048
      minibatch_size: 64
      training_epoch: 10
      normalize_v_targets: true
    memory:
      name: OnPolicyBatchReplay
    net:
      type: TorchArcNet
      arc:
        modules:
          body:
            Sequential:
              - LazyLinear:
                  out_features: 256
              - Tanh:
              - LazyLinear:
                  out_features: 256
              - Tanh:
        graph:
          input: x
          modules:
            body: [x]
          output: body
      shared: false
      hid_layers_activation: tanh
      init_fn: orthogonal_
      clip_grad_val: 0.5
      use_same_optim: true
      log_std_init: 0.0
      actor_init_std: 0.01
      critic_init_std: 1.0
      loss_spec:
        name: MSELoss
      optim_spec:
        name: AdamW
        lr: 3e-4
      gpu: auto
  env:
    name: ${env}
    num_envs: 16
    max_t: null
    max_frame: ${max_frame}
    normalize_obs: true
    normalize_reward: true
  meta:
    distributed: false
    log_frequency: 10000
    eval_frequency: 10000
    rigorous_eval: 0
    max_session: 4
    max_trial: 1
