# SAC Classic Control suite using TorchArcNet with YAML anchors
# Demonstrates how YAML anchors eliminate duplication across environments.
# Only the env-specific overrides differ between specs.

# Shared building blocks via YAML anchors
_arc_body: &arc_body
  modules:
    body:
      Sequential:
        - LazyLinear:
            out_features: 256
        - ReLU:
        - LazyLinear:
            out_features: 256
        - ReLU:
  graph:
    input: x
    modules:
      body: [x]
    output: body

_sac_net: &sac_net
  type: TorchArcNet
  arc: *arc_body
  clip_grad_val: null
  loss_spec:
    name: MSELoss
  optim_spec:
    name: Adam
    lr: 0.0003
  update_type: polyak
  polyak_coef: 0.005
  gpu: auto

_sac_algorithm: &sac_algorithm
  name: SoftActorCritic
  action_pdtype: Categorical
  action_policy: default
  gamma: 0.99
  training_frequency: 1
  training_start_step: 1000

_sac_memory: &sac_memory
  name: Replay
  batch_size: 256
  max_size: 100000
  use_cer: false

_sac_meta: &sac_meta
  distributed: false
  log_frequency: 500
  eval_frequency: 500
  max_session: 4
  max_trial: 1

# --- Specs: only env differs ---

sac_cartpole_arc:
  agent:
    name: SoftActorCritic
    algorithm: *sac_algorithm
    memory: *sac_memory
    net: *sac_net
  env:
    name: CartPole-v1
    num_envs: 4
    max_t: null
    max_frame: 200000
  meta: *sac_meta

sac_acrobot_arc:
  agent:
    name: SoftActorCritic
    algorithm: *sac_algorithm
    memory: *sac_memory
    net: *sac_net
  env:
    name: Acrobot-v1
    num_envs: 4
    max_t: null
    max_frame: 300000
  meta: *sac_meta

sac_mountaincar_arc:
  agent:
    name: SoftActorCritic
    algorithm: *sac_algorithm
    memory: *sac_memory
    net: *sac_net
  env:
    name: MountainCar-v0
    num_envs: 4
    max_t: null
    max_frame: 300000
  meta: *sac_meta
